### PR TITLE
add script to install and use Maven 3.3 instead of Travis' standard

### PR DESCRIPTION
**Pull request by sns-seb**
tested on Travis with SonarQube

### CODE REVIEW

**Comment by dgageot** [comment]
Hello @sns-seb Can you unassign me from this one :-) Thanks!

**Comment by simonbrandhof** [comment]
@sns-seb is this PR still required ?

**Comment by sns-seb** [comment]
@simonbrandhof it's not "required" since we build with maven 3.3 on Jenkins but as move more and more out of it, a time will come we will want to build on Travis with it too. Having this available in travis-utils will come in handy then. We should merge it.

**Comment by simonbrandhof** [comment]
ok, so go on with the merge.

**Pull request merged**
